import os
from xml.etree import ElementTree as ET

def generate_html_street_page(xml_file):
    tree = ET.parse("../MapaRuas-materialBase/texto/"+xml_file)
    root = tree.getroot()

    street_name = os.path.splitext(os.path.basename(xml_file))[0]

    street_html = f"""
<!doctype html>
<html>
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="./../custom.css" rel="stylesheet">
    <title>{street_name}</title>
    </head>

<body>
    <div class="w-full">
        <header>
            <h1>{street_name}</h1>
        </header>
        
"""
    street_html += """
        <div class="container mx-auto border-2 border-#6b7280 rounded my-8 shadow-lg"> 
            <div class="px-4 py-2">
                <h2 class="text-2xl underline">Informação da rua</h2>
            </div>
            <div class="px-8">
    """
    
    for elem in root.findall(".//meta/.*"):
        if elem.tag == 'número':
            street_html += f"""                
            <div class="flex flex-row items-center gap-2">
                    <p class="text-base font-bold">Número da Rua:</p>
                    <p>{elem.text}</p>
                </div>
            """
        elif elem.tag == 'nome':
            street_html += f"""                
            <div class="flex flex-row items-center gap-2">
                    <p class="text-base font-bold">Nome:</p> 
                    <p>{elem.text}</p>
                </div>
                """
    
    street_html += """
                <h2 class="text-base underline">Descrição da Rua:</h2>
                <div class="px-4 mb-4">
                """
    for para in root.findall(".//corpo/para"):
        street_html += f"<p>{ET.tostring(para).decode()}</p>\n"

    street_html += """
                </div>
            </div>
        </div>
    """

    street_html += """
        <h2 class="text-2xl text-red-600 font-bold">Informações das casas</h2>
        """
    street_html += "<ul>\n"
    for casa in root.findall(".//corpo/lista-casas/casa"):
        house_info = ""
        for child in casa:
            if child.tag == 'desc':
                para_element = child.find('para')
                if para_element is not None:
                    house_info += f"<li><strong>Descrição:</strong> {ET.tostring(para_element).decode()}</li>\n"
            elif child.tag == 'número':
                house_info += f"<h3>Casa {child.text}</h3>\n"
            elif child.tag == 'foro':
                house_info += f"<li><strong>Foro:</strong> {child.text}</li>\n"
            elif child.tag == 'enfiteuta':
                house_info += f"<li><strong>Enfiteuta:</strong> {child.text}</li>\n"    
            else:
                house_info += f"<li><strong>{child.tag}:</strong> {child.text}</li>\n"
        street_html += house_info

    street_html += "<h1>Imagens</h1>\n"
    for imagem in root.findall(".//corpo/figura"):
        path = imagem.find('imagem').attrib['path']
        caption = imagem.find('legenda').text
        street_html += f"<img src=\"../../MapaRuas-materialBase/{path[3:]}\" alt=\"{caption}\">\n"
        street_html += f"<p>{caption}</p>\n"

    street_html += """
            <footer>
                <h5>Generated by RuasApp::EngWeb2024::D1002</h5>
            </footer>
        
        </div>
    </body>
    </html>
    """

    with open(f"RuasPages/{street_name[7:]}.html", "w") as f:
        f.write(street_html)

def main():
    xml_files = sorted([filename for filename in os.listdir('../MapaRuas-materialBase/texto') if filename.endswith('.xml')])

    for xml_file in xml_files:
        generate_html_street_page(xml_file)

if __name__ == "__main__":
    main()