import os

header = """
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="./output.css" rel="stylesheet">
  <link href="./custom.css" rel="stylesheet">
</head>

<body>
    <div class="w-full">
        <header>
            <h3>Lista das Ruas de Braga</h3>
        </header>
        
        <div class="container mx-auto" style="margin-top:20px; margin-bottom:20px;">
            <ul class="list-none">
"""

ruas = []
for file in os.listdir("../MapaRuas-materialBase/texto/"):
    # acess the name of the file
    name = file.split(".")[0][7:]
    # add a space befere each capital letter
    final = name[0]
    for i in range(1, len(name)):
        if name[i].isupper():
            final += " " + name[i]
        else:
            final += name[i]
    ruas.append(final)

ruas.sort()
list = ""
for final in ruas:
    list += f"""
                <li class="rounded-box">
                    {final}
                </li>
    """

footer = """
            </ul>        
        </div>

        <footer>
            <h5>Generated by RuasApp::EngWeb2024::D1002</h5>
        </footer>
    
    </div>
</body>
</html>
"""

html = header + list + footer

with open("index.html", "w") as file:
    file.write(html)
